### ISSUE TITLE
txt

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_suggest_new#1]
для лексера `none` логично сохранение с расширением `.txt`

в LEXER_DETECT второй параметр путь к файлу
возможно сделать определение лексера для несохраненной вкладки?

**Comment by CudaText-addons** [comment]
>сохранение с расширением .txt

не уверен- это только на винде юзают. а делать так толлько для винды - не ок.

**Comment by CudaText-addons** [comment]
>в LEXER_DETECT второй параметр путь к файлу
возможно сделать определение лексера для несохраненной вкладки?

уже и так есть. Куд сама подставит расширение после имени в save-as dlg. нет?

**Comment by ildarkhasanshin** [comment]
> Куд сама подставит расширение после имени в save-as dlg. нет?

да
для `none` тока не подставляется
хотя протестил на st4 - там аналогично, все ок тогда
